### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by carson-katri**
Disables features unavailable on macOS.

### CODE REVIEW

**Comment by bcardarella** [comment]
Can we expand this to a larger feature for all platforms?

**Comment by carson-katri** [comment]
Sure, I'll look into doing that. It'll probably require rebuilding `liveview-native-core` for those platforms.

**Comment by bcardarella** [comment]
@carson-katri is that because of Intel?

**Comment by carson-katri** [comment]
It looks like it only builds for iOS/macOS in the Makefile: https://github.com/liveviewnative/liveview-native-core/blob/37d7970aaa3e0be32b40bf9ed895416ae17fc79b/Makefile.toml#L117

**Comment by bcardarella** [comment]
Ah ok I'll check into this

**Comment by carson-katri** [comment]
I added support for watchOS. It depends on https://github.com/liveviewnative/liveview-native-core/pull/5 and a new release of the xcframework (@shadowfacts is this automated?)

**Comment by carson-katri** [comment]
Ok, thanks. I'll get that uploaded.

**Review by shadowfacts — APPROVED** [review]

**Comment by carson-katri** [comment]
@shadowfacts The new version is released, so watchOS/macOS builds should be good to go

**Comment by shadowfacts** [comment]
Awesome, this looks good to me :+1:

**Comment by carson-katri** [comment]
I updated the workflow to make sure the package at least builds on macOS/watchOS. No tests run for them atm.

I also changed the saving of failed snapshots, they now are saved to the Report navigator in Xcode instead of writing to a temp directory.

**Pull request merged**
