### PR TITLE
GitHub Actions workflow for running tests

### PR DESCRIPTION
**Pull request by carson-katri**
This adds a simple CI workflow that runs tests on an iOS simulator.

### CODE REVIEW

**Comment by carson-katri** [comment]
@shadowfacts Looks like the build failed because there is no x86 build of the `liveview-native-core` framework? I imagine this may trip up users without M1/2 as well:
https://github.com/liveviewnative/liveview-client-swiftui/actions/runs/3942790937/jobs/6746857313#step:3:1086

**Comment by shadowfacts** [comment]
I've pushed a new version of liveview-native-core that includes the x86_64 artifacts, lets see if that does the trick...

**Comment by shadowfacts** [comment]
Well, the tests failed but they did indeed run, so things should be all set on the Intel front.

**Comment by carson-katri** [comment]
I switched to a UIKit-based snapshot so we can test Views that aren't rendered by SwiftUI.

Tests are also passing now.

**Review by shadowfacts — APPROVED** [review]

**Pull request merged**
